server:
    port: 6868 #服务端口 自定义
eureka:
    client:
      fetch-registry: false #是否从Eureka中获取注册信息
      register-with-eureka: false
      service-url: #Eureka客户端与Eureka服务端进行交互的地址
        defaultZone: http://127.0.0.1:${server.port}/eureka/
